### PR TITLE
Before & After Actions

### PR DESCRIPTION
**Pull request by Qakulukiam**
Added before and after actions to BuildConstructionPlan and Render. We can use this for logging and performance monitoring (and maybe more) in the future.

### CODE REVIEW

**Comment by Qakulukiam** [comment]
@domtra seems there's something wrong with a dependency in one of the travis tests: https://travis-ci.org/flyntwp/flynt-core/jobs/397247418

**Comment by domtra** [comment]
@Qakulukiam have you tried adding the min stability and prefer stable properties in the composer.json?

**Comment by Qakulukiam** [comment]
No, since I didn't change anything composer related I expected it to still work.. I'll try adding your proposed solution.

**Comment by Qakulukiam** [comment]
@domtra fixed this ci issue in #47

**Pull request merged**
